// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var themeSwitchContext = React.createContext(function (param) {
      
    });

var provider = themeSwitchContext.Provider;

function ThemeSwitchProvider(Props) {
  var value = Props.value;
  var children = Props.children;
  return React.createElement(provider, {
              value: value,
              children: children
            });
}

var make = ThemeSwitchProvider;

export {
  themeSwitchContext ,
  provider ,
  make ,
}
/* themeSwitchContext Not a pure module */
