// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from 'react';

const themeSwitchContext = React.createContext((param) => {});

const provider = themeSwitchContext.Provider;

function ThemeSwitchProvider(Props) {
  const {value} = Props;
  const {children} = Props;
  return React.createElement(provider, {
    value,
    children,
  });
}

const make = ThemeSwitchProvider;

export { make,provider, themeSwitchContext };
/* themeSwitchContext Not a pure module */
