// Generated by ReScript, PLEASE EDIT WITH CARE


var Button = {};

var Items = {};

var Item = {};

var Menu = {
  Button: Button,
  Items: Items,
  Item: Item
};

export {
  Menu ,
}
/* No side effect */
