// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

function useState(prim) {
  return React.useState(function () {
              return Curry._1(prim, undefined);
            });
}

function useTheme(key, initialValue) {
  var match = React.useState(function () {
        try {
          var v = localStorage.getItem(key);
          if (v == null) {
            return initialValue;
          } else {
            return v;
          }
        }
        catch (exn){
          return initialValue;
        }
      });
  var setStoredValue = match[1];
  var setValue = function (value) {
    try {
      localStorage.setItem(key, value);
      Curry._1(setStoredValue, (function (_prev) {
              return value;
            }));
      return ;
    }
    catch (raw_e){
      var e = Caml_js_exceptions.internalToOCamlException(raw_e);
      if (e.RE_EXN_ID === Js_exn.$$Error) {
        var msg = e._1.message;
        if (msg !== undefined) {
          console.log(msg);
          return ;
        } else {
          return ;
        }
      }
      throw e;
    }
  };
  return [
          match[0],
          setValue
        ];
}

export {
  useState ,
  useTheme ,
  
}
/* react Not a pure module */
