// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from 'react';
import * as Caml_js_exceptions from 'rescript/lib/es6/caml_js_exceptions.js';
import * as Curry from 'rescript/lib/es6/curry.js';
import * as Js_exn from 'rescript/lib/es6/js_exn.js';

const themeKey = 'RescriptTailwindTemplate_Theme';

function useTheme(defaultTheme) {
  const match = React.useState(() => {
    try {
      const v = localStorage.getItem(themeKey);
      if (v !== null) {
        return v;
      } 
        return defaultTheme;
      
    } catch (exn) {
      return defaultTheme;
    }
  });
  const setStoredTheme = match[1];
  const setTheme = function (themeName) {
    try {
      localStorage.setItem(themeKey, themeName);
      Curry._1(setStoredTheme, (_prev) => themeName);
      return;
    } catch (raw_e) {
      const e = Caml_js_exceptions.internalToOCamlException(raw_e);
      if (e.RE_EXN_ID === Js_exn.$$Error) {
        const msg = e._1.message;
        if (msg !== undefined) {
          console.log(msg);
          return;
        } 
          return;
        
      }
      throw e;
    }
  };
  return [match[0], setTheme];
}

export { themeKey, useTheme };
/* react Not a pure module */
