// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.js";

function useQueryParams(decoder, encoder, $$default, param) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var value;
  try {
    var v = decoder.decode(url.search);
    value = v.TAG === /* Ok */0 ? v._0 : $$default;
  }
  catch (raw_exn){
    Caml_js_exceptions.internalToOCamlException(raw_exn);
    value = $$default;
  }
  var setValue = function (params) {
    var url = new URLSearchParams(encoder.encode(params));
    RescriptReactRouter.push("/?" + url.toString());
  };
  return [
          value,
          setValue
        ];
}

export {
  useQueryParams ,
}
/* RescriptReactRouter Not a pure module */
