// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

var DecodeError = /* @__PURE__ */Caml_exceptions.create("Transform.DecodeError");

export {
  DecodeError ,
}
/* No side effect */
