// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Home(Props) {
  return React.createElement("div", {
              className: "flex flex-col justify-center items-center content-center\n    font-info text-base text-primary_600 py-10 text-center"
            }, React.createElement("span", {
                  className: "font-primary text-lg"
                }, "Welcome to ReScript-React Webpack Template"));
}

var make = Home;

export {
  make ,
  
}
/* react Not a pure module */
