// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import * as NavLink from "../components/NavLink.js";

function string(prim) {
  return prim;
}

function NotFound(Props) {
  return React.createElement("div", {
              className: "flex flex-col items-center pt-20 text-lg font-medium text-center text-slate-600"
            }, React.createElement("div", {
                  className: "w-full h-0 pb-40 relative"
                }, React.createElement("iframe", {
                      className: "absolute",
                      height: "100%",
                      src: "https://giphy.com/embed/0s4qt8wXIkI2S6nqqp",
                      width: "100%"
                    })), React.createElement("p", undefined, React.createElement("a", {
                      href: "https://giphy.com/gifs/thismorning-itv-this-morning-0s4qt8wXIkI2S6nqqp"
                    })), React.createElement("span", {
                  className: "my-5"
                }, "Hmm... this page doesn't exist. Please go to the home page by clicking\n        on the link below."), React.createElement("p", {
                  className: "font-nav font-medium text-900 underline cursor hover:text-700"
                }, React.createElement(NavLink.make, {
                      to: "/",
                      children: "Home"
                    })));
}

const make = NotFound;

export {
  make ,
  string ,
}
/* react Not a pure module */
