// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function About(Props) {
  return React.createElement("div", {
              className: "flex flex-col items-center gap-2 text-primary_600"
            }, React.createElement("h1", {
                  className: "text-xl"
                }, "Rescript-React Template with Tailwind"), React.createElement("a", {
                  className: "block text-primary_800 underline text-lg",
                  href: "https://github.com/nyinyithann/rescript-react-webpack-tailwind-template",
                  target: "_blank"
                }, "GitHub Repo"), React.createElement("div", undefined, React.createElement("pre", undefined, "\n  Installation\n\n- git clone https://github.com/nyinyithann/rescript-react-webpack-tailwind-template.git\n- cd rescript-react-webpack-tailwind-template\n- yarn install\n- yarn watch:res\n- yarn start\n- visit http://0.0.0.0:8080")));
}

var make = About;

export {
  make ,
  
}
/* react Not a pure module */
