// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.js";
import * as RescriptReactErrorBoundary from "@rescript/react/src/RescriptReactErrorBoundary.js";

function ErrorBoundary$Fallback(Props) {
  var error = Props.error;
  var info = Props.info;
  var onClick = function (param) {
    RescriptReactRouter.push("/");
    window.location.reload();
  };
  var tmp;
  if (error.RE_EXN_ID === Js_exn.$$Error) {
    var msg = error._1.message;
    tmp = msg !== undefined ? React.createElement("p", {
            className: "px-4 py-2 overflow-x-auto bs-scrollbar dark:dark-scrollbar"
          }, msg) : null;
  } else {
    tmp = null;
  }
  return React.createElement("div", {
              className: "w-full h-screen flex flex-col items-center justify-center bg-900 dark:bg-slate-900"
            }, React.createElement("article", {
                  className: "w-[50vw] h-auto flex flex-col border-[2px] border-100 rounded-lg shadow-slate-300 bg-200 dark:border-slate-500 dark:text-slate-200"
                }, React.createElement("header", {
                      className: "text-xl p-2 rounded-t-md bg-300 text-900 text-center dark:bg-slate-500 dark:text-slate-100 font-nav"
                    }, React.createElement("h2", undefined, "Sorry, something went wrong!")), React.createElement("nav", {
                      className: "flex items-center justify-center gap-2 py-4"
                    }, React.createElement("p", {
                          className: "text-800 text-lg"
                        }, "Would you try to reload the whole site?"), React.createElement("button", {
                          className: "px-4 bg-300 rounded-lg py-2 text-900 hover:bg-500 hover:text-50 dark:bg-slate-500 dark:text-slate-100 dark:hover:bg-slate-800",
                          type: "button",
                          onClick: onClick
                        }, "Reload")), React.createElement("details", {
                      className: "p-2 text-800 font-sans rounded-t-md hover:cursor-pointer"
                    }, React.createElement("summary", undefined, "Details"), tmp, React.createElement("p", {
                          className: "px-4 py-2 overflow-x-auto bs-scrollbar dark:dark-scrollbar"
                        }, "" + info.componentStack + ""))));
}

var Fallback = {
  make: ErrorBoundary$Fallback
};

function ErrorBoundary(Props) {
  var children = Props.children;
  return React.createElement(RescriptReactErrorBoundary.make, {
              children: children,
              fallback: (function (param) {
                  return React.createElement(ErrorBoundary$Fallback, {
                              error: param.error,
                              info: param.info
                            });
                })
            });
}

var make = ErrorBoundary;

export {
  Fallback ,
  make ,
}
/* react Not a pure module */
