// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReLogo$RescriptReactWebpackTailwindTemplate from "./ReLogo.bs.js";

function Greeting(Props) {
  return React.createElement("div", {
              className: "p-4 max-w-sm mx-auto bg-primary_500 rounded-xl shadow-md flex items-center space-x-4"
            }, React.createElement("div", {
                  className: "flex-shrink-0"
                }, React.createElement("div", {
                      className: "h-8 w-8"
                    }, React.createElement(ReLogo$RescriptReactWebpackTailwindTemplate.make, {}))), React.createElement("div", undefined, React.createElement("div", {
                      className: "text-base text-primary_100"
                    }, "Hello"), React.createElement("p", {
                      className: "text-sm text-primary_200"
                    }, "Welcome to ReScript")));
}

var make = Greeting;

export {
  make ,
  
}
/* react Not a pure module */
