// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Logo(Props) {
  var fillColor = Props.fillColor;
  return React.createElement("svg", {
              height: "24",
              width: "24",
              fill: fillColor,
              viewBox: "0 0 24 24",
              xmlns: "http://www.w3.org/2000/svg"
            }, React.createElement("path", {
                  clipRule: "evenodd",
                  d: "M3 3V9H21V3H3ZM19 5H5V7H19V5Z",
                  fill: fillColor,
                  fillRule: "evenodd"
                }), React.createElement("path", {
                  clipRule: "evenodd",
                  d: "M3 11V21H11V11H3ZM9 13H5V19H9V13Z",
                  fill: fillColor,
                  fillRule: "evenodd"
                }), React.createElement("path", {
                  d: "M21 11H13V13H21V11Z",
                  fill: fillColor
                }), React.createElement("path", {
                  d: "M13 15H21V17H13V15Z",
                  fill: fillColor
                }), React.createElement("path", {
                  d: "M21 19H13V21H21V19Z",
                  fill: fillColor
                }));
}

var make = Logo;

export {
  make ,
  
}
/* react Not a pure module */
