// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Logo(Props) {
  return React.createElement("svg", {
              className: "h-6 w-6 fill-klor-900",
              fill: "none",
              stroke: "fill-klor-200",
              strokeWidth: "1",
              viewBox: "0 0 24 24",
              xmlns: "http://www.w3.org/2000/svg"
            }, React.createElement("path", {
                  d: "M15.042 21.672L13.684 16.6m0 0l-2.51 2.225.569-9.47 5.227 7.917-3.286-.672zm-7.518-.267A8.25 8.25 0 1120.25 10.5M8.288 14.212A5.25 5.25 0 1117.25 10.5",
                  strokeLinecap: "round",
                  strokeLinejoin: "round"
                }));
}

var make = Logo;

export {
  make ,
}
/* react Not a pure module */
