// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";
import * as ReLogo$RescriptReactWebpackTailwindTemplate from "./ReLogo.bs.js";

function string(prim) {
  return prim;
}

function NavBar(Props) {
  var setTheme = Props.setTheme;
  return React.createElement("nav", {
              className: "bg-primary_500 py-1 fixed inset-x-0 shadow flex-1"
            }, React.createElement("div", {
                  className: "max-w-6xl mx-auto px-4"
                }, React.createElement("div", {
                      className: "flex justify-between"
                    }, React.createElement("div", {
                          className: "flex space-x-2"
                        }, React.createElement("div", {
                              className: "pt-1 px-3 h-12 w-12"
                            }, React.createElement(ReLogo$RescriptReactWebpackTailwindTemplate.make, {})), React.createElement("div", {
                              className: "flex items-center text-primary_200 "
                            }, React.createElement("button", {
                                  className: "focus:outline-none hover:bg-primary_600 hover:rounded",
                                  type: "button",
                                  onClick: (function (param) {
                                      return RescriptReactRouter.push("/");
                                    })
                                }, React.createElement("a", {
                                      className: "py-5 px-3 hover:text-primary_100"
                                    }, "Home")), React.createElement("button", {
                                  className: "focus:outline-none hover:bg-primary_600 hover:rounded",
                                  type: "button",
                                  onClick: (function (param) {
                                      return RescriptReactRouter.push("about");
                                    })
                                }, React.createElement("a", {
                                      className: "py-5 px-3 hover:text-primary_100"
                                    }, "About")))), React.createElement("div", {
                          className: "hidden sm:flex items-center space-x-2"
                        }, React.createElement("button", {
                              className: "theme-btn",
                              style: {
                                background: "#6B7280"
                              },
                              type: "button",
                              onClick: (function (param) {
                                  return Curry._1(setTheme, (function (param) {
                                                return "theme-gray";
                                              }));
                                })
                            }), React.createElement("button", {
                              className: "theme-btn",
                              style: {
                                background: "#EF4444"
                              },
                              type: "button",
                              onClick: (function (param) {
                                  return Curry._1(setTheme, (function (param) {
                                                return "theme-red";
                                              }));
                                })
                            }), React.createElement("button", {
                              className: "theme-btn",
                              style: {
                                background: "#3B82F6"
                              },
                              type: "button",
                              onClick: (function (param) {
                                  return Curry._1(setTheme, (function (param) {
                                                return "theme-blue";
                                              }));
                                })
                            }), React.createElement("button", {
                              className: "theme-btn",
                              style: {
                                background: "#F59E0B"
                              },
                              type: "button",
                              onClick: (function (param) {
                                  return Curry._1(setTheme, (function (param) {
                                                return "theme-yellow";
                                              }));
                                })
                            }), React.createElement("button", {
                              className: "theme-btn",
                              style: {
                                background: "#10B981"
                              },
                              type: "button",
                              onClick: (function (param) {
                                  return Curry._1(setTheme, (function (param) {
                                                return "theme-green";
                                              }));
                                })
                            })))));
}

var make = NavBar;

export {
  string ,
  make ,
  
}
/* react Not a pure module */
