// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.js";

function NavLink(Props) {
  var to = Props.to;
  var children = Props.children;
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var path;
  if (match) {
    var path$1 = Belt_List.reduce(url.path, "", (function (acc, p) {
            return acc + "/" + p;
          }));
    path = path$1.replace(/\/$/g, "");
  } else {
    path = "/";
  }
  var baseStyle = "focus:outline-none h-8 rounded-sm hover:bg-400/60 dark:hover:bg-slate-500 px-3 text-900";
  var className = path === to ? "" + baseStyle + " bg-400/60 dark:bg-slate-500" : baseStyle;
  return React.createElement("button", {
              className: className,
              type: "button",
              onClick: (function (e) {
                  e.preventDefault();
                  RescriptReactRouter.push(to);
                })
            }, children);
}

var make = NavLink;

export {
  make ,
}
/* react Not a pure module */
