// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.js";
import * as React from "react";
import * as Belt_List from "rescript/lib/es6/belt_List.js";

function NavLink(Props) {
  const {to} = Props;
  const {children} = Props;
  const url = RescriptReactRouter.useUrl(undefined, undefined);
  const match = url.path;
  let path;
  if (match) {
    const path$1 = Belt_List.reduce(url.path, "", ((acc, p) => `${acc  }/${  p}`));
    path = path$1.replace(/\/$/g, "");
  } else {
    path = "/";
  }
  const baseStyle = "focus:outline-none h-8 rounded-sm hover:bg-400/60 dark:hover:bg-slate-500 mx-1 px-3 text-900";
  const className = path === to ? `${  baseStyle  } bg-400/60 dark:bg-slate-500` : baseStyle;
  return React.createElement("button", {
              className,
              type: "button",
              onClick (e) {
                  e.preventDefault();
                  RescriptReactRouter.push(to);
                }
            }, children);
}

const make = NavLink;

export {
  make ,
}
/* react Not a pure module */
