// Generated by ReScript, PLEASE EDIT WITH CARE

import RescriptBrandmarkSvg from "../../public/brand/rescript-brandmark.svg";

var make = RescriptBrandmarkSvg;

export {
  make ,
  
}
/* make Not a pure module */
