// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import * as Loading from "./Loading.js";

function SuspensionLoader(Props) {
  const {children} = Props;
  return React.createElement(React.Suspense, {
              fallback: React.createElement(Loading.make, {
                    className: "w-[4rem] h-[3rem] stroke-[0.2rem] p-3 stroke-klor-200 text-700 dark:fill-slate-600 dark:stroke-slate-400 dark:text-900"
                  }),
              children
            });
}

const make = SuspensionLoader;

export {
  make ,
}
/* react Not a pure module */
