// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./pages/Home.js";
import * as About from "./pages/About.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as NavBar from "./components/NavBar.js";
import * as NotFound from "./pages/NotFound.js";
import * as ThemeHook from "./hooks/ThemeHook.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.js";
import * as ThemeSwitchProvider from "./providers/ThemeSwitchProvider.js";

function string(prim) {
  return prim;
}

function useState(prim) {
  return React.useState(function () {
              return Curry._1(prim, undefined);
            });
}

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var component = match ? (
      match.hd === "about" ? (
          match.tl ? React.createElement(NotFound.make, {}) : React.createElement(About.make, {})
        ) : React.createElement(NotFound.make, {})
    ) : React.createElement(Home.make, {});
  var match$1 = ThemeHook.useTheme("theme-slate");
  return React.createElement(ThemeSwitchProvider.make, {
              value: match$1[1],
              children: React.createElement("div", {
                    className: "" + match$1[0] + " flex flex-col"
                  }, React.createElement(NavBar.make, {}), React.createElement("div", {
                        className: "py-20 bg-white h-screen p-3"
                      }, component))
            });
}

var make = App;

export {
  string ,
  useState ,
  make ,
  
}
/* Home Not a pure module */
