// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.js";
import * as React from "react";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Js_promise from "rescript/lib/es6/js_promise.js";

import * as NavBar from "./components/NavBar.js";
import * as SuspensionLoader from "./components/SuspensionLoader.js";
import * as ThemeHook from "./hooks/ThemeHook.js";
import * as NotFound from "./pages/NotFound.js";
import * as ThemeSwitchProvider from "./providers/ThemeSwitchProvider.js";

function string(prim) {
  return prim;
}

function useState(prim) {
  return React.useState(() => Curry._1(prim, undefined));
}

function App(Props) {
  const lazyHome = React.createElement(React.lazy((param) => {
            const __x = import("./pages/Home.js");
            return Js_promise.then_(((comp) => Promise.resolve({
                                      default: comp.make
                                    })), __x);
          }), undefined);
  const lazyAbout = React.createElement(React.lazy((param) => {
            const __x = import("./pages/About.js");
            return Js_promise.then_(((comp) => Promise.resolve({
                                      default: comp.make
                                    })), __x);
          }), undefined);
  const url = RescriptReactRouter.useUrl(undefined, undefined);
  const match = url.path;
  const component = match ? (
      match.hd === "about" ? (
          match.tl ? React.createElement(NotFound.make, {}) : React.createElement(SuspensionLoader.make, {
                  children: lazyAbout
                })
        ) : React.createElement(NotFound.make, {})
    ) : React.createElement(SuspensionLoader.make, {
          children: lazyHome
        });
  const match$1 = ThemeHook.useTheme("theme-slate");
  return React.createElement(ThemeSwitchProvider.make, {
              value: match$1[1],
              children: React.createElement("div", {
                    className: `${  match$1[0]  } flex flex-col`
                  }, React.createElement(NavBar.make, {}), React.createElement("div", {
                        className: "py-20 bg-white h-screen dark:bg-slate-500"
                      }, component))
            });
}

const make = App;

export {
  make ,
  string ,
  useState ,
}
/* react Not a pure module */
