// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.js";
import * as React from "react";
import * as ReactDom from "react-dom";

import '../style/main.css'
;

var root = document.querySelector("#root");

if (!(root == null)) {
  var prim0 = React.createElement(React.StrictMode, {
        children: React.createElement(App.make, {})
      });
  ReactDom.render(prim0, root);
}

export {
  
}
/*  Not a pure module */
