// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as App$RescriptReactWebpackTailwindTemplate from "./components/App.bs.js";

import '../style/main.css'
;

var root = document.querySelector("#react");

if (!(root == null)) {
  var prim = React.createElement(App$RescriptReactWebpackTailwindTemplate.make, {});
  ReactDom.render(prim, root);
}

export {
  
}
/*  Not a pure module */
